### ISSUE TITLE
C++ Ubuntu version make error on jetson xavier nx  

### ISSUE THREAD

**Issue by ye0571** [engcang/ros-yolo-sort#1]
Hi,

I encounter make error on  jetson xavier nx  

ros-yolov3-sort/SORT/cpp_ubuntu/build$ cmake .. && make
......

[ 80%] Building CXX object CMakeFiles/sort_cpp_node.dir/src/main.cpp.o
/home/nxm/ros-yolov3-sort/SORT/cpp_ubuntu/src/main.cpp: In function ‘void TestSORT(std::__cxx11::string, bool)’:
/home/nxm/ros-yolov3-sort/SORT/cpp_ubuntu/src/main.cpp:389:41: error: ‘CV_WINDOW_NORMAL’ was not declared in this scope
             cv::namedWindow("SORT-C++", CV_WINDOW_NORMAL);
                                         ^~~~~~~~~~~~~~~~
CMakeFiles/sort_cpp_node.dir/build.make:62: recipe for target 'CMakeFiles/sort_cpp_node.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/sort_cpp_node.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/sort_cpp_node.dir/all' failed
make[1]: *** [CMakeFiles/sort_cpp_node.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

It seems CV_WINDOW_NORMAL not deifned, where should I add the define?

**Comment by ye0571** [comment]
compile OK after modified CV_WINDOW_NORMAL as WINDOW_NORMAL

**Comment by engcang** [comment]
> compile OK after modified CV_WINDOW_NORMAL as WINDOW_NORMAL

Good to hear that you successfully made it!
Thanks a lot man!
