### ISSUE TITLE
ROS - C++ is not working yet.

### ISSUE THREAD

**Issue by musaceylan** [engcang/ros-yolo-sort#3]
hi @engcang 

great implementation. 
just saying I cant wait to see the full implementation of  ROS - C++.

Thank you

**Comment by engcang** [comment]
@musaceylan 
hmmmmm Well I didn't know there is someone waiting for the implementation of it.
I thought it is unnecessary, cause even Python version works super fast enough.

Well I think I will implement it when I feel the need!
maybe next year...?

**Comment by musaceylan** [comment]
thank you for your swift reply @engcang 
you dont need to feel obligated :), I will be working on it next week, but I am not sure that I could finish it before you.
