### ISSUE TITLE
When I run the yolov4 tiny. Launch file, this problem has bothered me for a long time. How can I solve it

### ISSUE THREAD

**Issue by xiaoyang12333** [engcang/ros-yolo-sort#5]
[darknet_ros-1] process has died [pid 7205, exit code -6, cmd /home/rong/ce42/devel/lib/darknet_ros/darknet_ros camera/rgb/image_raw:=usb_cam/image_raw __name:=darknet_ros __log:=/home/rong/.ros/log/86a42996-41f4-11ec-85b4-cf13d8f5a8b0/darknet_ros-1.log].
log file: /home/rong/.ros/log/86a42996-41f4-11ec-85b4-cf13d8f5a8b0/darknet_ros-1*.log

**Comment by engcang** [comment]
Hi @xiaoyang12333

I cannot check the detailed error messages and cannot solve the problem with this little information.
Can you explain the situation in more details please?
